#!/bin/bash
#PBS -q arm
#PBS -l select=MC_NODES:ncpus=MC_PPN
#PBS -l walltime=01:00:00
#PBS -o out/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles.log

cd /home/br-hwaugh/repos/minicombust_app_tx2_gcc12/

source env.sh

HEADER="cells       real_time  total_time     performance   mem_bandwidth"

echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-interpolate_nodal_data.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-particle_interpolation_data.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-solve_spray_equations.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-update_particle_positions.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-emitted_particles.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-updated_flow_field.log
echo $HEADER > results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-minicombust.log

for (( MESH=MC_LOW; MESH <= MC_HIGH; MESH *= 2 ))
do
    ACTUAL_MESH_SIZE=$(( 2*$MESH*$MESH*$MESH ))
    echo "Running $MESH mesh experiment with $ACTUAL_MESH_SIZE cells"
    module unload cray-python/3.8.5.1
    aprun -n MC_PROCS -N MC_PPN ./bin/minicombust $(( 1 * MC_PROCS / 16 )) MC_PARTICLES $MESH -1
    module load cray-python/3.8.5.1

    echo "Running: python analysis/get_roofline_cmd.py TX2 MC_ROOFLINE MC_PPN | tee /tmp/roofline.log"
    python analysis/get_roofline_cmd.py TX2 MC_ROOFLINE MC_PPN | tee /tmp/roofline.log

    cat /tmp/roofline.log | grep "    interpolate_nodal_data"      >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-interpolate_nodal_data.log
    cat /tmp/roofline.log | grep "    particle_interpolation_data" >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-particle_interpolation_data.log
    cat /tmp/roofline.log | grep "    solve_spray_equations"       >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-solve_spray_equations.log
    cat /tmp/roofline.log | grep "    update_particle_positions"   >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-update_particle_positions.log
    cat /tmp/roofline.log | grep "    emitted_particles"           >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-emitted_particles.log
    cat /tmp/roofline.log | grep "    updated_flow_field"          >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-updated_flow_field.log
    cat /tmp/roofline.log | grep "    minicombust"                 >> results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-minicombust.log


    sed -i "s/ *interpolate_nodal_data/$ACTUAL_MESH_SIZE/g"       results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-interpolate_nodal_data.log
    sed -i "s/ *particle_interpolation_data/$ACTUAL_MESH_SIZE/g"  results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-particle_interpolation_data.log
    sed -i "s/ *solve_spray_equations/$ACTUAL_MESH_SIZE/g"        results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-solve_spray_equations.log
    sed -i "s/ *update_particle_positions/$ACTUAL_MESH_SIZE/g"    results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-update_particle_positions.log
    sed -i "s/ *emitted_particles/$ACTUAL_MESH_SIZE/g"            results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-emitted_particles.log
    sed -i "s/ *updated_flow_field/$ACTUAL_MESH_SIZE/g"           results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-updated_flow_field.log
    sed -i "s/ *minicombust/$ACTUAL_MESH_SIZE/g"                  results/tx2-weak_mesh-MC_NODESnodes-MC_PPNppn-MC_PARTICLESparticles-minicombust.log
done

echo "Running python analysis/weak_mesh_graphs.py MC_NODES MC_PPN MC_PARTICLES"
python analysis/weak_mesh_graphs.py MC_NODES MC_PPN MC_PARTICLES