#!/bin/bash
#PBS -q arm
#PBS -l select=MC_NODES:ncpus=MC_PPN
#PBS -l walltime=01:00:00
#PBS -o out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier.log

cd /home/br-hwaugh/repos/minicombust_app_tx2_gcc12/

source env.sh

HEADER="particles       real_time  total_time     performance   mem_bandwidth"

echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
echo $HEADER > results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log

for (( PARTICLES=MC_LOW; PARTICLES <= MC_HIGH; PARTICLES *= 2 ))
do
    echo "Running $PARTICLES particles experiment"
    module unload cray-python/3.8.5.1
    aprun -n MC_PROCS -N MC_PPN ./bin/minicombust $(( 3 * MC_PROCS / 4 )) $PARTICLES MC_CELLS_MODIFIER -1
    module load cray-python/3.8.5.1

    echo "Running: python analysis/get_roofline_cmd.py TX2 MC_ROOFLINE MC_PPN | tee /tmp/roofline.log"
    python analysis/get_roofline_cmd.py TX2 MC_ROOFLINE MC_PPN | tee /tmp/roofline.log

    cat /tmp/roofline.log | grep "    interpolate_nodal_data"      >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
    cat /tmp/roofline.log | grep "    particle_interpolation_data" >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
    cat /tmp/roofline.log | grep "    solve_spray_equations"       >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
    cat /tmp/roofline.log | grep "    update_particle_positions"   >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
    cat /tmp/roofline.log | grep "    emitted_particles"           >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
    cat /tmp/roofline.log | grep "    updated_flow_field"          >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
    cat /tmp/roofline.log | grep "    minicombust"                 >> results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log

    sed -i "s/ *interpolate_nodal_data/$PARTICLES/g"       results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
    sed -i "s/ *particle_interpolation_data/$PARTICLES/g"  results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
    sed -i "s/ *solve_spray_equations/$PARTICLES/g"        results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
    sed -i "s/ *update_particle_positions/$PARTICLES/g"    results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
    sed -i "s/ *emitted_particles/$PARTICLES/g"            results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
    sed -i "s/ *updated_flow_field/$PARTICLES/g"           results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
    sed -i "s/ *minicombust/$PARTICLES/g"                  results/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log
done

echo "Running python analysis/weak_particle_graphs.py MC_NODES MC_PPN MC_CELLS_MODIFIER"
python analysis/weak_particle_graphs.py MC_NODES MC_PPN MC_CELLS_MODIFIER