#!/bin/bash
#PBS -q arm
#PBS -l select=MC_NODES:ncpus=MC_PPN
#PBS -l walltime=01:00:00
#PBS -o out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier.log

cd /home/br-hwaugh/repos/minicombust_app_tx2_gcc12/

source env.sh

HEADER="particles       real_time  total_time     performance   mem_bandwidth"

echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
echo $HEADER > out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log

for (( PARTICLES=MC_LOW; PARTICLES <= MC_HIGH; PARTICLES *= 2 ))
do
    echo "Running $PARTICLES particles experiment"
    aprun -n MC_PROCS -N MC_PPN ./bin/minicombust $PARTICLES MC_CELLS_MODIFIER
    python analysis/get_roofline_cmd.py TX2 MC_ROOFLINE MC_PPN | tee /tmp/roofline.log

    cat /tmp/roofline.log | grep "    interpolate_nodal_data"      >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
    cat /tmp/roofline.log | grep "    particle_interpolation_data" >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
    cat /tmp/roofline.log | grep "    solve_spray_equations"       >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
    cat /tmp/roofline.log | grep "    update_particle_positions"   >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
    cat /tmp/roofline.log | grep "    emitted_particles"           >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
    cat /tmp/roofline.log | grep "    updated_flow_field"          >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
    cat /tmp/roofline.log | grep "    minicombust"                 >> out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log

    sed -i "s/ *interpolate_nodal_data/$PARTICLES/g"       out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-interpolate_nodal_data.log
    sed -i "s/ *particle_interpolation_data/$PARTICLES/g"  out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-particle_interpolation_data.log
    sed -i "s/ *solve_spray_equations/$PARTICLES/g"        out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-solve_spray_equations.log
    sed -i "s/ *update_particle_positions/$PARTICLES/g"    out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-update_particle_positions.log
    sed -i "s/ *emitted_particles/$PARTICLES/g"            out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-emitted_particles.log
    sed -i "s/ *updated_flow_field/$PARTICLES/g"           out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-updated_flow_field.log
    sed -i "s/ *minicombust/$PARTICLES/g"                  out/tx2-weak_particles-MC_NODESnodes-MC_PPNppn-MC_CELLS_MODIFIERcells_modifier-minicombust.log
done